name: Rust - Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true

      - name: Run rustfmt
        run: cargo fmt --check
        working-directory: ./windiff_cli

      - name: Run clippy
        run: cargo clippy
        working-directory: ./windiff_cli
